# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  config.vm.define "puppetserver" do |puppetserver|
    puppetserver.vm.hostname = "puppetserver.mjmax.ppp"
    puppetserver.vm.network "private_network", ip: "10.10.10.10"
    puppetserver.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "playbooks/puppetserver.yml"
    end
    puppetserver.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.define "clientprod" do |clientprod|
    clientprod.vm.hostname = "clientprod.mjmax.ppp"
    clientprod.vm.network "private_network", ip: "10.10.10.20"
    clientprod.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "playbooks/clientprod.yml"
    end
  end

   config.vm.define "clientqa" do |clientqa|
    clientqa.vm.hostname = "clientqa.mjmax.ppp"
    clientqa.vm.network "private_network", ip: "10.10.10.30"
    clientqa.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "playbooks/clientqa.yml"
    end
  end
end
