---
  - name: Install epel-release
    yum: name=epel-release state=present

  - name: Install required packages
    yum: name={{ item }} state=present
    register: result
    with_items:
      - htop
      - git
      - lsof
      - bash-completion*
      - vim
      - ntp
      - mc
      - nmap
      - tcpdump

  - name: Start and enable ntpd
    service: name=ntpd state=started enabled=yes

  - name: Copy hosts file to servers
    template:
      src: ../templates/hosts.j2
      dest: /etc/hosts
      owner: root
      mode: 0644
