---
- hosts: all
  become: yes

  tasks:

  - include: common.yml

  - name: Install puppetagent
    yum:
      name: puppet-agent
      state: latest

  - name: Copy config
    template:
      src: ../templates/clientqa.conf.j2
      dest: /etc/puppetlabs/puppet/puppet.conf
      owner: root
      mode: 0644

  # - name: Start puppetagent
  #   service:
  #     name: puppet-agent
  #     state: started
  #     enabled: yes
