---
- hosts: all
  become: yes 
  tasks: 

  - name: Install epel-release
    yum: name=epel-release state=present

  - name: Install requared sortware
    yum: name={{ item }} state=present
    register: result
    with_items:
      - htop
      - git
      - lsof
      - bash-completion*
      - docker
      - vim 
      - python-pip
      - centos-release-gluster310
      - parted
      - ntp

  - name: Start and enable ntpd
    service: name=ntpd state=started enabled=yes

  - name: Copy hosts file to servers
    template:
      src: templates/hosts.j2
      dest: /etc/hosts
      owner: root
      mode: 0644
      
  - name: Install gluster
    yum: name=glusterfs-server state=present
 
  - name: Create filesystem on /dev/sdb
    filesystem:
      fstype: xfs
      dev: /dev/sdb
   
  - name: Create a share folder
    file: 
      path: /share
      state: directory
      mode: 0755

  - name:  Add the share to fstab
    mount:
      name: /share
      src: /dev/sdb
      fstype: xfs
      state: mounted

  - name: Start and enable glusterfs-sever
    service:
      name: glusterd
      state: started
      enabled: yes 

  - name: Create a gluster volume folder
    file: 
      path: /share/gv0
      state: directory
      mode: 0755
