---
- hosts: all
  become: yes

  tasks:

  - include: common.yml

  - name: Download chef server
    get_url:
      url: https://packages.chef.io/files/stable/chef-server/12.15.8/el/7/chef-server-core-12.15.8-1.el7.x86_64.rpm
      dest: /tmp/chef-server.rpm

  - name: Install chefserver
    yum:
       name: /tmp/chef-server.rpm
       state: present
