# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "chefserver" do |chefserver|
    chefserver.vm.hostname = "chefserver.mjmax.ppp"
    chefserver.vm.network "private_network", ip: "10.10.10.10"
    chefserver.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    chefserver.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbooks/chefserver.yml"
    end
  end

  config.vm.define "chefdk" do |chefdk|
    chefdk.vm.hostname = "chefdk.mjmax.ppp"
    chefdk.vm.network "private_network", ip: "10.10.10.20"
    chefdk.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbooks/chefdk.yml"
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.hostname = "centos.mjmax.ppp"
    centos.vm.network "private_network", ip: "10.10.10.30"
    centos.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbooks/centos.yml"
    end
  end
  
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu.mjmax.ppp"
    ubuntu.vm.network "private_network", ip: "10.10.10.40"
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbooks/ubuntu.yml"
    end
  end
end
